apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: my-cluster

spec:
  interval: 1m
  path: ./spring-boot-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
