apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters--personal/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: spring-boot-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/spring-boot-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
